name: matomo-nginx
type: service
from: php-nginx
title: Nginx (Matomo)

update: auto
    
labels:
- matomo

build:
  dockerfile: Dockerfile

configs:
- name: preset
  title: Matomo preset
  filepath: /etc/gotpl/preset/matomo.conf.tmpl
  config: preset.conf.tmpl

env:
- name: NGINX_VHOST_PRESET
  value: matomo
