name: matomo-nginx
type: service
from: nginx
title: Nginx (Matomo)

update: auto

build: null

settings: null

labels:
- matomo

configs:
- name: preset 
  title: Matomo preset
  filepath: /etc/gotpl/preset/matomo.conf.tmpl
  config: preset.conf.tmpl

env:
- name: NGINX_VHOST_PRESET
  value: matomo
